---
- name: "Customizing Parrot"
  hosts: localhost
  connection: local
  roles:
    - uninstall_tools
    - install_tools
    # configure_tmux
    - customize_terminal
    - customize_browser
    - configure_logging
    - configure_system
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user_id }}"
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
    #        - DEVSENSE.phptools-vscode
    #        - GitHub.copilot
            - snyk-security.snyk-vulnerability-scanner
