---
# - name: "Remove unofficial docker images"
#   ansible.builtin.package:
#     name:
#       - docker.io
#       - docker-compose
#       - docker-doc
#       - podman-docker
#     state: absent
#   register: docker_remove
#   become: true

- name: "Remove Packages"
  ansible.builtin.package:
    name:
      - codium  # we install code
      - netexec # we install it using uvx
    state: absent
  become: true

# - name: "Remove Containerd/Runc"
#   ansible.builtin.package:
#     name:
#       - containerd
#       - runc
#     state: absent
#   when: docker_remove.changed
#   become: true
