---
- name: "Already exists? Release Binary from github: {{ item.filename }}"
  ansible.builtin.stat:
    path: "{{ item.location }}/{{ item.filename }}"
  register: release_bin

- name: Debug
  debug:
    msg: "{{ not release_bin.stat.exists }}  {{ item.upgrade }}"

- name: Download Release Block
  when: not release_bin.stat.exists or item.upgrade
  block:
    - name: Create temporary build directory
      ansible.builtin.tempfile:
        state: directory
      register: build_dir

    - name: "Copying python script to download github releases"
      ansible.builtin.copy:
        src: "files/githubdownload.py"
        dest: "{{ build_dir.path }}/githubdownload.py"
        owner: root
        group: root
        mode: "0755"
      become: true

    - name: "Downloading github releases: {{ item.repo }}"
      ansible.builtin.command: >
        {{ build_dir.path }}/githubdownload.py
        {{ item.repo }}
        {{ item.regex }}
        {{ item.location }}
        {% if item.filename is defined %}{{ item.filename }}{% endif %}
      async: 45
      poll: 2
      become: true
      changed_when: true

    - name: "Make file executable: {{ item.filename }}"
      ansible.builtin.file:
        path: "{{ item.location }}/{{ item.filename }}"
        mode: "a+x"
      become: true

    - name: Remove temporary build directory
      ansible.builtin.file:
        path: "{{ build_dir.path }}"
        state: absent
      when: build_dir.path is defined
