---
- name: "APT Stuff"
  ansible.builtin.include_tasks: apt-stuff.yml

- name: "Install Go Tools"
  ansible.builtin.include_tasks: go-tools.yml
  loop:
    - { name: kerbrute, url: github.com/ropnop/kerbrute@master, upgrade: false }

- name: "Install Python uvx Tools"
  ansible.builtin.include_tasks: python-tools.yml
  loop:
    - { name: 'impacket', url: 'git+https://github.com/fortra/impacket.git', upgrade: false }
    - { name: 'netexec', url: 'git+https://github.com/Pennyw0rth/NetExec.git', upgrade: false }
    - { name: 'certipy-ad', url: 'git+https://github.com/ly4k/Certipy.git', upgrade: false}
    - { name: 'bloodhound-ce', url: 'git+https://github.com/dirkjanm/BloodHound.py.git@bloodhound-ce', upgrade: false }
    - { name: 'podman-compose', url: 'git+https://github.com/containers/podman-compose.git', upgrade: false}
    - { name: 'bloodyAD', url: 'git+https://github.com/CravateRouge/bloodyAD.git', upgrade: false}

- name: "Checkout GithubRepos"
  ansible.builtin.include_tasks: checkout-github-repos.yml
  loop:
    - { repo: "https://github.com/Flangvik/SharpCollection", location: "/opt/SharpCollection", upgrade: false }
    - { repo: "https://github.com/danielmiessler/SecLists", location: "/opt/SecLists", upgrade: false }

- name: "Install Release Binaries from github"
  ansible.builtin.include_tasks: install-github-release.yml
  loop:
    - { repo: "jpillora/chisel", regex: "_linux_amd64.gz", location: "/opt/chisel", filename: chisel, upgrade: false }
    - { repo: "jpillora/chisel", regex: "_windows_amd64.gz", location: "/opt/chisel", filename: chisel.exe, upgrade: false }
    # - { repo: "jpillora/chisel",  regex: "_darwin_amd64", location: "/opt/chisel", filename: "chisel_osx", upgrade: false }
    - { repo: "carlospolop/PEASS-ng", regex: "linpeas.sh", location: "/opt/peas", filename: linpeas.sh, upgrade: false }
    - { repo: "carlospolop/PEASS-ng", regex: "winPEASx64.exe", location: "/opt/peas", filename: winPEASx64.exe, upgrade: false }
    - { repo: "WithSecureLabs/chainsaw", regex: "chainsaw_all_", location: "/opt/", filename: chainsaw, upgrade: false }
    # - { repo: "BloodHoundAD/BloodHound", regex: "BloodHound-linux-x64.zip", location: "/opt/", filename: TODO }
    - { repo: "mikefarah/yq", regex: "^yq_linux_amd64$", location: "/opt/", filename: "yq", upgrade: false}

- name: "Install Tools from Ruby Gems"
  ansible.builtin.include_tasks: gem-tools.yml
  loop:
    - logger
    - stringio
    - winrm
    - builder
    - erubi
    - gssapi
    - gyoku
    - httpclient
    - logging
    - little-plugger
    - nori
    - rubyntlm
    - winrm-fs
    - evil-winrm
  tags:
    - gems

- name: "Install Bloodhound CE"
  ansible.builtin.include_tasks: bloodhound.yml
