---
- name: "Already installed: {{ item.name }}"
  ansible.builtin.stat:
    path: ~/.local/share/uv/tools/{{ item.name }}
  changed_when: false
  register: uv_tool

- name: "Install/Upgrade uvx tool: {{ item.name }}"
  ansible.builtin.command: uv tool install {{ item.url }}
  when: not uv_tool.stat.exists or item.upgrade
  changed_when: true
