# code language=ansible
---
- name: "Read current mate terminal profiles"
  community.general.dconf:
    key: "/org/mate/terminal/global/profile-list"
    state: "read"
  register: "profile_list"

- name: "Profile_list was not set, setting"
  ansible.builtin.set_fact:
    profile_list:
      value: '["default"]'
  when: profile_list.value is none

- name: "Adding our profile"
  ansible.builtin.set_fact:
    new_profile_list: "{{ profile_list.value | regex_replace(']$', \", 'video']\") }}"

- name: "Writing updated profile list"
  community.general.dconf:
    key: "/org/mate/terminal/global/profile-list"
    value: "{{ new_profile_list }}"
  when: "'video' not in profile_list.value"

- name: "Restoring Video Profile from Dump"
  ansible.builtin.command: "dconf load /org/mate/terminal/profiles/video/ < {{ role_path }}/files/dconf-dump-video"
  when: "'video' not in profile_list.value"
  changed_when: true
