---
# - name: "Remove unofficial docker images"
#   package:
#     name: 
#       - docker.io
#       - docker-compose
#       - docker-doc
#       - podman-docker
#     state: absent
#   register: docker_remove  
#   become: true
#   become_method: sudo

- name: "Remove NetExec - We want to use pipx for this"
  package:
    name: 
      - netexec
    state: absent
  become: true
  become_method: sudo

# - name: "Remove Containerd/Runc"
#   package:
#     name: 
#       - containerd
#       - runc
#     state: absent
#   when: docker_remove.changed
#   become: true
#   become_method: sudo


# TODO uninstall tools that i dont use
# tor anonsurf etc

# codium!?
# default screencapture!?

